version: '3.8'

services:
  db:
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_jwt
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT_FORWARD:-9102}:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=rootpw
    ports:
      - '${DBADMIN_PORT_FORWARD:-9103}:80'
    depends_on:
      - db
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
volumes:
  dbdata:
